@Restaurants.API_HostAddress = https://localhost:7001

GET {{Restaurants.API_HostAddress}}/api/restaurants

###
POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "Name": "Spicy 2 Delights",
  "Description": " A culinary experience like no other",
  "Category": " Fine Dining",
  "HasDelivery": true,
  "ContactEmail": "info@gourmetdelights.com",
  "ContactNumber": "555-123-4567",
  "City": "Metropolis",
  "Street": "456 Gourmet Avenue",
  "PostalCode": "54321"

}
###
DELETE {{Restaurants.API_HostAddress}}/api/restaurants/5

###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/4
Content-Type: application/json

{
  "Name": "Sample patch",
  "Description": "This is a sample restaurant description.",
  "HasDelivery": true
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/1/dishes
Content-Type: application/json

{
  "Name": "Spaghetti Bolognese  second",
  "Description": "added Classic Italian pasta dish with rich meat sauce",
  "Price": 227.99,
  "KiloCalories": 7750
}

###

GET https://localhost:7001/api/restaurants/1/dishes/10

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/1/dishes/7

###

@restaurantId=1
GET {{Restaurants.API_HostAddress}}/api/restaurants/1/dishes

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/4/dishes
Content-Type: application/json

{
  "Name": "Spaghetti Bolognese  second",
  "Description": "added Classic Italian pasta dish with rich meat sauce",
  "Price": 227.99,
  "KiloCalories": 7750
}

###
@restaurantId=99
DELETE {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantId}}/dishes

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/1/dishes

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/{restaurantId}/dishes
Content-Type: application/json

{
  //CreateDishCommand
}

###
