@Restaurants.API_HostAddress = https://localhost:7001

GET {{Restaurants.API_HostAddress}}/api/restaurants

###
POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "Name": "Spicy 2 Delights",
  "Description": " A culinary experience like no other",
  "Category": " Fine Dining",
  "HasDelivery": true,
  "ContactEmail": "info@gourmetdelights.com",
  "ContactNumber": "555-123-4567",
  "City": "Metropolis",
  "Street": "456 Gourmet Avenue",
  "PostalCode": "54321"

}
###
DELETE {{Restaurants.API_HostAddress}}/api/restaurants/5
