name: Restaurant Api CD

on: 
  
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name:  Checkout
        uses: actions/checkout@v6.0.2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v5.2.0
        with:
          dotnet-version: 8.0.x
      - name: Restore Dependancies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore -c Release
      - name: Publich
        run: dotnet publish ./src/Restaurants.API/Restaurants.API.csproj --no-build -o $DOTNET_ROOT/api
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-artifact 
          path: $DOTNET_ROOT/api

 # Job 2 - Deploy Dev
  deploy-dev:
     runs-on: ubuntu-latest
     needs: build

     steps: 
       - name: Download a Build Artifact
         uses: actions/download-artifact@v4
         with:
          name: api-artifact 
          path: $DOTNET_ROOT/api
       - name:  Deploy to Dev
         uses: Azure/webapps-deploy@v2.2.19
         with:
          app-name: restaurants-api-dev
          publish-profile: ${{secrets.PUBLISH_PROFILE_DEV}}
     


 # Job 2 - Deploy Dev
  deploy-prod:
     runs-on: ubuntu-latest
     needs: build

     steps: 
       - name: Download a Build Artifact
         uses: actions/download-artifact@v4
         with:
          name: api-artifact 
          path: $DOTNET_ROOT/api
       - name:  Deploy to Prod
         uses: Azure/webapps-deploy@v2.2.19
         with:
          app-name: restaurants-api-prod
          publish-profile: ${{secrets.PUBLISH_PROFILE_PROD}}
   













        
